### ISSUE TITLE
Missing or Incorrectly Placed Deliverable 2 Documentation

### ISSUE THREAD

**Issue by PythonTenure** [UsmanGhias/FinalYearProject#1]
---
### Problem:
The Deliverable 2 PDF document is missing from its designated location within the project documentation. This is causing confusion and hindering the project progress.

### Issue Description:
The Deliverable 2 PDF, which is a crucial component of the project, cannot be found in its expected location within the project documentation. This misplaced or absent document is preventing team members from accessing essential information related to Deliverable 2. 

### Impact:
The absence of the Deliverable 2 PDF is creating the following issues:
* Delays in project progress due to missing information.
* Confusion among team members about the requirements and specifications of Deliverable 2.
* Potential errors or inconsistencies in the development process.

### Expected Resolution:
The Deliverable 2 PDF should be located in the specified documentation folder. The document should be accessible to all relevant team members.

**Comment by PythonTenure** [comment]
**Thank you for the detailed solution!** Your steps for correctly placing and accessing the Deliverable 2 documentation are spot on. I've already implemented your suggestions and relocated the PDF to the designated folder.

**Comment by UsmanGhias** [comment]
**Thank you for the detailed solution!** Your steps for correctly placing and accessing the Deliverable 2 documentation are spot on. I've already implemented your suggestions and relocated the PDF to the designated folder.

**Comment by UsmanGhias** [comment]
# Issue Resolved `:)`

**Comment by PythonTenure** [comment]
Yes its done
